### ISSUE TITLE
Only working locally

### ISSUE THREAD

**Issue by jspurney** [jspurney/davey-quiz#1]
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=app
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:68:12
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:2082:17
    at ensure (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:2006:38)
    at module (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:2080:14)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:4617:22
    at forEach (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:321:20)
    at loadModules (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:4601:5)
    at createInjector (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:4523:19)
    at doBootstrap (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:1758:20)
    at bootstrap (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js:1779:12)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=app&p1=Error%3A%20%…cloudflare.com%2Fajax%2Flibs%2Fangular.js%2F1.5.8%2Fangular.js%3A1779%3A12)

**Comment by jspurney** [comment]
When `DOMContentLoaded` fires, `ng-app` automatically calls `angular.bootstrap`. and since my other scripts needed to run my app had not loaded yet, it caused my app to crash.  I fix the issue by manually bootstrapping my angular application (once all scripts have been loaded).
